### ISSUE TITLE
Support for Chrome/Chrome Driver

### ISSUE THREAD

**Issue by kostajh** [arknoll/ansible-role-selenium#3]
Any chance you'd entertain adding this?

**Comment by kevinquillen** [comment]
Came here looking for exactly this. How would one go about implementing it?

**Comment by oxyc** [comment]
@justinlevi got this working with the following steps https://github.com/geerlingguy/drupal-vm/issues/481

**Comment by grasmash** [comment]
Some related code...

```
#!/usr/bin/env bash
# Installs chromedriver for Linux 64 bit systems.
# Requires Trusty or higher.

# Scripts expect argument specifying bin dir.
BIN_DIR=$1

if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  # Download google chrome.
  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  sudo dpkg -i --force-depends google-chrome-stable_current_amd64.deb

  # Download and install chromedriver.
  LATEST=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
  wget http://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
  unzip chromedriver_linux64.zip
  chmod +x chromedriver
  mv -f chromedriver $BIN_DIR
fi
```

**Comment by geerlingguy** [comment]
I have some tests for chrome + the rest so far (haven't done any testing with chromedriver yet).

Will submit a PR in a few minutes once I verify it's working.

**Comment by geerlingguy** [comment]
PR #14 adds support; I tested on Ubuntu 16 only for now; but through #13 (I'll get to that soon), we could add automated tests for all the other supported OSes too :)
