### ISSUE TITLE
xvfb is not run with selenium_xvfb_args in ubuntu 16.04

### ISSUE THREAD

**Issue by jeff1985** [arknoll/ansible-role-selenium#36]
ubuntu 16.04 uses systemd unit file. the template selenium-unit.j2 is missing the selenium_xvfb_args parameter!

the result is that xvfb is run with the default 640x480x8 resolution:

> * selenium.service - selenium test framework
   Loaded: loaded (/etc/systemd/system/selenium.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-04-17 23:54:16 CEST; 24s ago
 Main PID: 7519 (xvfb-run)
   CGroup: /system.slice/selenium.service
           |-7519 /bin/sh /usr/bin/xvfb-run /usr/bin/java -client -jar /opt/selenium/selenium-server-standalone-2.53.1.jar
           |-7542 Xvfb :99 -screen 0 640x480x8 -nolisten tcp -auth /tmp/xvfb-run.xNbcGG/Xauthority
           `-7560 /usr/bin/java -client -jar /opt/selenium/selenium-server-standalone-2.53.1.jar

**Comment by arknoll** [comment]
Good find! Thank you for the issue.
