### ISSUE TITLE
Problem enabling selenium on Ubuntu 16.04

### ISSUE THREAD

**Issue by iainhouston** [arknoll/ansible-role-selenium#7]
Not seen this with Ubuntu 14.04. Do we need to register `selenium.service` in a new way for Ubuntu 16.04 so that the `run` step works?

```
- name: run
  service: name=selenium state=started enabled=yes
  tags: [configuration, selenium, selenium-run]
```

Error: 

```
fatal: [dbapc]: FAILED! => {"changed": false, "failed": true, "msg": 
"Error when trying to enable selenium: rc=1 selenium.service is not a native service,
 redirecting to systemd-sysv-install\nExecuting /lib/systemd/systemd-sysv-install enable 
 selenium\ninsserv: warning: script 'selenium' missing LSB tags and overrides\nupdate-rc.d: 
 error: selenium Default-Start contains no runlevels, aborting.\n"}
```

**Comment by iainhouston** [comment]
Doesn't error when `selenium_version: 2.46.0` but does error when `selenium_version: 2.52.0`

**Comment by geerlingguy** [comment]
There's also a new `2.53.0` release—does that work any better?

**Comment by boinkster** [comment]
Had this issue on Drupal VM when turning on Selenium on an existing VM... Changing to 2.53.0 in the config.yml and running vagrant provision fixed the issue.

**Comment by geerlingguy** [comment]
See: https://github.com/arknoll/ansible-role-selenium/pull/8 — hopefully it works!

**Comment by arknoll** [comment]
Updating to 2.53.0 as default. Thank you!

**Comment by swichers** [comment]
I was still getting this with 2.53. Ultimately I wound up downgrading Ubuntu so I could move forward. I did find this comment which gives some insight into a fix: https://github.com/elastic/ansible-elasticsearch/issues/70#issuecomment-194527183
